TOPDIR ?= ../..
include $(TOPDIR)/.config

$(EIBD_SUPPORT)_SRC += services/eibd/eibd.c
$(EIBD_SUPPORT)_ECMD_SRC += services/eibd/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
